- name: configure catalogue component
  hosts: catalogue
  become: yes
  tasks:
  - name: Disable default node js
    ansible.builtin.command: dnf module disable nodejs -y
  - name:  enable nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Install node js
    ansible.builtin.dnf:
    name: nodejs
    state: present

  - name: create a system user
    ansible.builtin.user:
    name: roboshop
    shell: /sbin/nologin
    system: true
    home: /app

  - name: create the directory
    ansible.builtin.file:
    path: /app
    state: directory

  - name: download the catalogue file
    ansible.builtin.get.url:
    url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
    dest: /tmp/catalogue.zip

  - name: unzip the downloaded file
    ansible.builtin.unarchive:
    src: /tmp/catalogue.zip
    dest: /app
    remote_src: true
  