- name: configure user component
  hosts: user
  become: yes
  tasks:
  - name: Disable default node js
    ansible.builtin.command: dnf module disable nodejs -y

  - name:  enable nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Install node js
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create a system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: create the directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download the user file
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip 
      dest: /tmp/user.zip

  - name: unzip the downloaded file
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: true

  - name: install dependencies
    community.general.npm:
      path: /app

  - name: copy user service to system directory
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: systemctl daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true
    
  - name: start and enable the service
    ansible.builtin.service:
      name: user
      state: started
      enabled: yes